INSERT INTO PARAMETER_GROUP
(
	ID
)
VALUES
(
	'NBODY_PARAMETER_GROUP'
);


INSERT INTO PARAMETER_TYPE
(
	PARAMETER_GROUP_ID,
	NAME,
	MIN_VALUE,
	MAX_VALUE
)
SELECT
	'NBODY_PARAMETER_GROUP',
	'' || GENERATE_SERIES || '.VX',
	-100,
	100
FROM
	GENERATE_SERIES(1,5)

UNION ALL
SELECT
	'NBODY_PARAMETER_GROUP',
	'' || GENERATE_SERIES || '.VY',
	-100,
	100
FROM
	GENERATE_SERIES(1,5)
UNION ALL
	SELECT
	'NBODY_PARAMETER_GROUP',
	'' || GENERATE_SERIES || '.VZ',
	-100,
	100
FROM
	GENERATE_SERIES(1,5);

INSERT INTO EXPERIMENT_SCRIPT
(
	ID,
	SCRIPT,
	LAUNCHER,
	PARAMETER_GROUP_ID,
	ALLOWED_DURATION_SECONDS
)
VALUES
(
	'NBODY_SCRIPT',
	'SCORE = PARAMETERDATA[''1.X'']]',
	'PYTHON',
	'NBODY_PARAMETER_GROUP',
	300
);

INSERT INTO EXPERIMENT_GROUP
(
	GROUP_CONFIG_ID,-- CHARACTER VARYING (128) NOT NULL REFERENCES GROUP_CONFIG(ID),
	MAX_EXPERIMENT_COUNT,-- BIGINT NOT NULL,
	EXPERIMENT_SCRIPT_ID-- CHARACTER VARYING (128) REFERENCES EXPERIMENT_SCRIPT(ID),
)
VALUES
(
	'BASIC_DETERMINISTIC',
	100000,
	'NBODY_SCRIPT'
)