CREATE OR REPLACE FUNCTION FILL_IN_MISSING_PARAMETERS(PARAM_EXPERIMENT_ID BIGINT) RETURNS VOID
AS
$$
BEGIN
	INSERT INTO PARAMETER
	(
		EXPERIMENT_ID,
		PARAMETER_TYPE_ID,
		PARAMETER_VALUE
	)
	SELECT
		E.ID,
		PT.ID,
		(RANDOM()) * (PT.MAX_VALUE - PT.MIN_VALUE) + PT.MIN_VALUE
	FROM
		EXPERIMENT E
	JOIN
		EXPERIMENT_GROUP EG
	ON
		E.EXPERIMENT_GROUP_ID = EG.ID
	JOIN
		EXPERIMENT_SCRIPT ES
	ON
		ES.ID = EG.EXPERIMENT_SCRIPT_ID
	JOIN
		PARAMETER_GROUP PG
	ON
		PG.ID = ES.PARAMETER_GROUP_ID
	JOIN
		PARAMETER_TYPE PT
	ON
		PT.PARAMETER_GROUP_ID = PG.ID
	WHERE NOT EXISTS
	(
		SELECT
			1
		FROM
			PARAMETER P_INNER
		WHERE
			P_INNER.EXPERIMENT_ID = PARAM_EXPERIMENT_ID
		AND
			P_INNER.PARAMETER_TYPE_ID = P_OUTER.EXPERIMENT_TYPE_ID
	)
	AND
		E.ID = PARAM_EXPERIMENT_ID;
	
END
$$
LANGUAGE PLPGSQL