 CREATE TABLE GROUP_CONFIG
 (
 	
	ID CHARACTER VARYING(128) PRIMARY KEY,
 	STARTING_POPULATION_SIZE INT NOT NULL,
 	NUMBER_OF_RECENT_CONTENDERS INT NOT NULL,
 	NUMBER_OF_RANDOM_CONTENDERS INT NOT NULL,
 	NUMBER_OF_BEST_CONTENDERS INT NOT NULL,
 	PERFORMANCE_BIAS REAL NOT NULL,
 	RESAMPLE_BIAS REAL NOT NULL,
 	RESAMPLE_PROBABILITY REAL NOT NULL,
 	CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
 	MODIFIED TIMESTAMP NOT NULL DEFAULT NOW()
 );


CREATE TABLE PARAMETER_GROUP
(
	ID CHARACTER VARYING (128) PRIMARY KEY,
	CREATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE EXPERIMENT_SCRIPT
(
	ID CHARACTER VARYING (128) PRIMARY KEY,
	SCRIPT TEXT NOT NULL,
	PARAMETER_GROUP_ID CHARACTER VARYING(128) NOT NULL REFERENCES PARAMETER_GROUP(ID),
	LAUNCHER TEXT NOT NULL,
	CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFIED TIMESTAMP NOT NULL DEFAULT NOW ()
);

CREATE TABLE EXPERIMENT_GROUP
(
	ID BIGSERIAL PRIMARY KEY,
	GROUP_CONFIG_ID CHARACTER VARYING (128) NOT NULL REFERENCES GROUP_CONFIG(ID),
	MAX_EXPERIMENT_COUNT BIGINT NOT NULL,
	EXPERIMENT_SCRIPT_ID CHARACTER VARYING (128) REFERENCES EXPERIMENT_SCRIPT(ID),
	CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFIED TIMESTAMP NOT NULL DEFAULT NOW()
);



CREATE TABLE EXPERIMENT
(
	ID BIGSERIAL PRIMARY KEY,
	EXPERIMENT_GROUP_ID BIGINT NOT NULL REFERENCES EXPERIMENT_GROUP(ID),
	-- TODO: AUTOCOMPUTE MEAN_SCORE
	MEAN_SCORE REAL NOT NULL DEFAULT 0,
	NET_SCORE REAL NOT NULL DEFAULT 0,
	TOTAL_TRIALS INT NOT NULL DEFAULT 0,
	CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFIED TIMESTAMP NOT NULL DEFAULT NOW()
	
);

CREATE TABLE RESULT
(
	ID BIGSERIAL PRIMARY KEY,
	EXPERIMENT_ID BIGINT NOT NULL REFERENCES EXPERIMENT(ID),
	SCORE REAL NOT NULL,
	DATA TEXT,
	CREATED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PARAMETER_TYPE
(
	ID BIGSERIAL PRIMARY KEY,
	PARAMETER_GROUP_ID CHARACTER VARYING (128) NOT NULL REFERENCES PARAMETER_GROUP(ID),
	NAME CHARACTER VARYING(1000),
	MIN_VALUE REAL,
	MAX_VALUE REAL,
	CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
	MODIFIED TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PARAMETER
(
	ID BIGSERIAL PRIMARY KEY,
	PARAMETER_TYPE_ID BIGINT REFERENCES PARAMETER_TYPE(ID),
	PARAM_VALUE REAL NOT NULL,
	PARENT_PARAMETER_A BIGINT REFERENCES PARAMETER(ID),
	PARENT_PARAMETER_B BIGINT REFERENCES PARAMETER(ID),
	CREATED TIMESTAMP NOT NULL DEFAULT NOW()
);