CREATE OR REPLACE FUNCTION EXPERIMENT_AFTER_UPDATE() RETURNS TRIGGER AS 
$$
BEGIN
	
	NEW.MODIFIED = NOW();
	NEW.MEAN_SCORE = NEW.NET_SCORE / NEW.TOTAL_TRIALS;
	RETURN NEW;
END
$$
LANGUAGE PLPGSQL;


CREATE OR REPLACE  FUNCTION PARAMETER_TYPE_AFTER_UPDATE() RETURNS TRIGGER AS
$$
BEGIN
	NEW.MODIFIED = NOW();
	RETURN NEW;
END
$$
LANGUAGE PLPGSQL;

CREATE OR REPLACE  FUNCTION EXPERIMENT_GROUP_AFTER_UPDATE() RETURNS TRIGGER AS
$$
BEGIN
	NEW.MODIFIED = NOW();
	RETURN NEW;
END
$$
LANGUAGE PLPGSQL;

CREATE OR REPLACE  FUNCTION GROUP_CONFIG_AFTER_UPDATE() RETURNS TRIGGER AS
$$
BEGIN
	NEW.MODIFIED = NOW();
	RETURN NEW;
END
$$
LANGUAGE PLPGSQL;

CREATE OR REPLACE  FUNCTION EXPERIMENT_SCRIPT_AFTER_UPDATE() RETURNS TRIGGER AS
$$
BEGIN
	NEW.MODIFIED = NOW();
	RETURN NEW;
END
$$
LANGUAGE PLPGSQL;


