DROP TABLE PARAMETER;
DROP TABLE PARAMETER_TYPE;
DROP TABLE PARAMETER_GROUP;

DROP TABLE RESULT;
DROP TABLE EXPERIMENT;

DROP TABLE EXPERIMENT_GROUP;
DROP TABLE GROUP_CONFIG;
DROP TABLE EXPERIMENT_SCRIPT;


