DROP TABLE PARAMETER CASCADE;
DROP TABLE PARAMETER_TYPE;

DROP TABLE RESULT;
DROP TABLE EXPERIMENT;

DROP TABLE EXPERIMENT_GROUP;
DROP TABLE GROUP_CONFIG;
DROP TABLE EXPERIMENT_SCRIPT;
DROP TABLE PARAMETER_GROUP CASCADE;